export const SET_MANAGE_TRANSACTIONS_LIST2STATE = 'ADM/SET_MANAGE_TRANSACTIONS_LIST2STATE';
export const SET_MANAGE_TRANSACTIONS_DETAIL2STATE = 'ADM/SET_MANAGE_TRANSACTIONS_DETAIL2STATE';
export const CLEAR_MANAGE_TRANSACTIONS_DETAIL2STATE = 'ADM/CLEAR_MANAGE_TRANSACTIONS_DETAIL2STATE';
export const PUT_MANAGE_TRANSACTIONS_DETAIL2STATE = 'ADM/PUT_MANAGE_TRANSACTIONS_DETAIL2STATE';

// Admin Remote API
export const GET_MANAGE_TRANSACTIONS_LIST = 'ADM/GET_MANAGE_TRANSACTIONS_LIST ';
export const GET_MANAGE_TRANSACTIONS_DETAILS_BY_ID = 'ADM/GET_MANAGE_TRANSACTIONS_DETAILS_BY_ID';
export const UPDATE_MANAGE_TRANSACTIONS_DETAILS = 'ADM/UPDATE_MANAGE_TRANSACTIONS_DETAILS';
export const DELETE_MANAGE_TRANSACTIONS_LIST = 'ADM/DELETE_MANAGE_TRANSACTIONS_LIST';
export const DELETE_MANAGE_TRANSACTIONS_BY_ID = 'ADM/DELETE_MANAGE_TRANSACTIONS_BY_ID';
export const UPDATE_MANAGE_TRANSACTIONS_STATUS = 'ADM/UPDATE_MANAGE_TRANSACTIONS_STATUS';

export const UNMOUNT_CLEAR_MANAGE_TRANSACTIONS_DETAILS = 'ADM/UNMOUNT_CLEAR_MANAGE_TRANSACTIONS_DETAILS';

