export const SET_ADVERTISING_LIST2STATE = 'ADM/SET_ADVERTISING_LIST2STATE';
export const SET_ADVERTISING_DETAIL2STATE = 'ADM/SET_ADVERTISING_DETAIL2STATE';
export const CLEAR_ADVERTISING_DETAIL2STATE = 'ADM/CLEAR_ADVERTISING_DETAIL2STATE';

export const PUT_ADVERTISING_DETAIL2STATE = 'ADM/PUT_ADVERTISING_DETAIL2STATE';

// Admin Remote API
export const GET_ADVERTISING_LIST = 'ADM/GET_ADVERTISING_LIST ';
export const GET_ADVERTISING_DETAILS_BY_ID = 'ADM/GET_ADVERTISING_DETAILS_BY_ID';
export const UPDATE_ADVERTISING_DETAILS = 'ADM/UPDATE_ADVERTISING_DETAILS';
export const DELETE_ADVERTISING_LIST = 'ADM/DELETE_ADVERTISING_LIST';
export const DELETE_ADVERTISING_BY_ID = 'ADM/DELETE_ADVERTISING_BY_ID';
export const UPDATE_ADVERTISING_STATUS = 'ADM/UPDATE_ADVERTISING_STATUS';

export const CREATE_ADVERTISING = 'ADM/CREATE_ADVERTISING';

export const UNMOUNT_CLEAR_ADVERTISING_DETAILS = 'ADM/UNMOUNT_CLEAR_ADVERTISING_DETAILS';

export const PUBLISH_ADVERTISING_ITEM = 'ADM/PUBLISH_ADVERTISING_ITEM';
