export const SET_VEHICLES_LIST2STATE = 'CTT/SET_VEHICLES_LIST2STATE';
export const SET_VEHICLE_DETAILS2STATE = 'CTT/SET_VEHICLE_DETAIL2STATE';
export const CLEAR_VEHICLE_DETAILS2STATE = 'CTT/CLEAR_VEHICLE_DETAIL2STATE';
export const SET_VEHICLE_FORM_DATA = 'CTT/SET_VEHICLE_FORM_DATA';

// Admin Remote API
export const GET_VEHICLES_LIST = 'CTT/GET_VEHICLES_LIST ';
export const GET_VEHICLE_DETAILS_BY_ID = 'CTT/GET_VEHICLES_DETAILS_BY_ID';
export const UPDATE_VEHICLE_DETAILS = 'CTT/UPDATE_VEHICLES_DETAILS';
export const DELETE_VEHICLES_LIST = 'CTT/DELETE_VEHICLES_LIST';
export const DELETE_VEHICLE_BY_ID = 'CTT/DELETE_VEHICLE_BY_ID';
export const UPDATE_VEHICLE_STATUS = 'CTT/UPDATE_VEHICLE_STATUS';
export const UPDATE_VEHICLES_STATUS = 'CTT/UPDATE_VEHICLES_STATUS';
export const CREATE_VEHICLE = 'CTT/CREATE_VEHICLE';
export const SUSPEND_VEHICLE_BY_ID = 'CTT/SUSPEND_VEHICLE_BY_ID';

export const UNMOUNT_CLEAR_VEHICLE_DETAILS = 'CTT/UNMOUNT_CLEAR_VEHICLE_DETAILS';

