export const FETCH_DISCOUNT_DETAIL = 'ADM/DISCOUNT/FETCH_DISCOUNT_DETAIL';
export const SET_DISCOUNT_DETAIL = 'ADM/DISCOUNT/SET_DISCOUNT_DETAIL';
export const DELETE_DISCOUNT = 'ADM/DISCOUNT/DELETE_DISCOUNT';
