
export const GET_WASTE_TYPE_LIST = 'ADM/GET_WASTE_TYPE_LIST';
export const PUT_WASTE_TYPE_LIST2STATE = 'ADM/PUT_WASTE_TYPE_LIST2STATE';
export const UPDATE_WASTE_TYPE_IMAGE = 'ADM/UPDATE_WASTE_TYPE_IMAGE';
