
export const GET_DASHBOARD_SUMMARY = 'CTT/GET_DASHBOARD_SUMMARY';
export const PUT_DASHBOAD_SUMMARY2STATE = 'CTT/PUT_DASHBOARD_SUMMARY2STATE';
export const GET_DASHBOARD_REVENUE = 'CTT/GET_DASHBOARD_REVENUE';
export const PUT_DASHBOARD_REVENUE2STATE = 'CTT/PUT_DASHBOARD_REVENUE2STATE';

