export const SET_COLLECTION_REQUESTS_LIST2STATE = 'ADM/SET_COLLECTION_REQUESTS_LIST2STATE';
export const SET_COLLECTION_REQUESTS_DETAIL2STATE = 'ADM/SET_COLLECTION_REQUESTS_DETAIL2STATE';
export const CLEAR_COLLECTION_REQUESTS_DETAIL2STATE = 'ADM/CLEAR_COLLECTION_REQUESTS_DETAIL2STATE';
export const PUT_COLLECTION_REQUESTS_DETAIL2STATE = 'ADM/PUT_COLLECTION_REQUESTS_DETAIL2STATE';

export const GET_COLLECTION_REQUESTS_LIST = 'ADM/GET_COLLECTION_REQUESTS_LIST ';
export const GET_COLLECTION_REQUESTS_DETAILS_BY_ID = 'ADM/GET_COLLECTION_REQUESTS_DETAILS_BY_ID';
export const UPDATE_COLLECTION_REQUESTS_DETAILS = 'ADM/UPDATE_COLLECTION_REQUESTS_DETAILS';
export const DELETE_COLLECTION_REQUESTS_LIST = 'ADM/DELETE_COLLECTION_REQUESTS_LIST';
export const DELETE_COLLECTION_REQUESTS_BY_ID = 'ADM/DELETE_COLLECTION_REQUESTS_BY_ID';
export const UPDATE_COLLECTION_REQUESTS_STATUS = 'ADM/UPDATE_COLLECTION_REQUESTS_STATUS';

export const UNMOUNT_CLEAR_COLLECTION_REQUESTS_DETAILS = 'ADM/UNMOUNT_CLEAR_COLLECTION_REQUESTS_DETAILS';

export const UPDATE_BIN_STATUS = 'ADM/UPDATE_BIN_STATUS';
export const UPDATE_BIN_COLLECTION_REQUEST_STATUS = 'ADM/UPDATE_BIN_COLLECTION_REQUEST_STATUS';