export const FETCH_DISPUTE_DETAIL = 'ADM/DISPUTE/FETCH_DISPUTE_DETAIL';
export const SET_DISPUTE_DETAIL = 'ADM/DISPUTE/SET_DISPUTE_DETAIL';

export const ADD_DISPUTE_NOTE = 'ADM/DISPUTE/ADD_DISPUTE_NOTE';
export const FETCH_DISPUTE_NOTES = 'ADM/DISPUTE/FETCH_DISPUTE_NOTES';
export const SET_NOTE_STATE = 'ADM/DISPUTE/SET_NOTE_STATE';
export const DELETE_DISPUTE_NOTE = 'ADM/DISPUTE/DELETE_DISPUTE_NOTE';
export const UPDATE_DISPUTE_NOTE = 'ADM/DISPUTE/UPDATE_DISPUTE_NOTE';
