export const CONTRACTOR_RESET_PASSWORD = 'CONTRACTOR/RESET_PASSWORD';
export const CONTRACTOR_UPDATE_PASSWORD = 'CONTRACTOR/UPDATE_PASSWORD';
export const CONTRACTOR_UPDATED_PROCESSING = 'CONTRACTOR/UPDATED_PROCESSING';

