/**
 * Get vehicle detail
 */
export const GET_VEHICLE_DETAIL = 'vehicle/GET_VEHICLE_DETAIL';
export const GET_VEHICLE_DETAIL_REQUESTING = 'vehicle/GET_VEHICLE_DETAIL_REQUESTING';
export const GET_VEHICLE_DETAIL_SUCCESSED = 'vehicle/GET_VEHICLE_DETAIL_SUCCESSED';
export const GET_VEHICLE_DETAIL_FAILED = 'vehicle/GET_VEHICLE_DETAIL_FAILED';

/**
 * Set edit mode
 */
export const TOGGLE_EDIT_MODE = 'vehicle/TOGGLE_EDIT_MODE';

export const RESET_DATA = 'vehicle/RESET_DATA';

/**
 * Submit Profile
 */
export const SUBMIT_VEHICLE_DETAIL = 'vehicle/SUBMIT_VEHICLE_DETAIL';
export const SUBMIT_VEHICLE_DETAIL_REQUESTING = 'vehicle/SUBMIT_VEHICLE_DETAIL_REQUESTING';
export const SUBMIT_VEHICLE_DETAIL_SUCCESSED = 'vehicle/SUBMIT_VEHICLE_DETAIL_SUCCESSED';
export const SUBMIT_VEHICLE_DETAIL_FAILED = 'vehicle/SUBMIT_VEHICLE_DETAIL_SUCCESSED';

/**
 * Get contractors
 */
export const GET_CONTRACTOR_LIST = 'vehicle/GET_CONTRACTOR_LIST';
export const GET_CONTRACTOR_LIST_REQUESTING = 'vehicle/GET_CONTRACTOR_LIST_REQUESTING';
export const GET_CONTRACTOR_LIST_SUCCESSED = 'vehicle/GET_CONTRACTOR_LIST_SUCCESSED';
export const GET_CONTRACTOR_LIST_FAILED = 'vehicle/GET_CONTRACTOR_LIST_FAILED';
